### ISSUE TITLE
3 - New feature request - Backup

### ISSUE THREAD

**Issue by onlykey** [trustcrypto/OnlyKey-Chrome-App#11]
I have been thinking for awhile that we need some sort of backup feature. After doing some research I think a per slot download of a CSV file is probably the best. I am looking into KeePass CSV format so we could export/import to and from KeePass. The way this feature would work is there would be a third button on each of the slot configuration forms. So the three buttons would be wipe, backup, and submit. Once a user fills in all the fields they can click the backup before clicking submit. Backup would prompt the user "Before backing up sensitive data ensure that you are using a computer that you trust, preferably not connected to the internet. Save backup files to a secure location on your computer, preferably an encrypted container (i.e. Veracrypt/Truecrypt) or an encrypted removable drive that can be stored in a secure area." The prompt would have two options, continue to backup or exit. Continue to backup would pop up a saveas window to save the backup file to wherever the user wants to. The name of the file would be OnlyKey-Slot#-timestamp.csv, i.e. OnlyKey-1A-5-25-2016-15-46-53.csv. The content of the file would be just what is in the app fields separated by commas i.e. Mylabel,myusername,1,1,mypassword,2,1,g,JBSWY3DPEHPK3PXP. The next thing after this would be import that would fill the fields with values when you load a file.

**Comment by onlykey** [comment]
I tested this out with KeePass and using generic CSV import we can import the following format using default settings.
![image](https://cloud.githubusercontent.com/assets/18121756/15547752/33018ca8-2273-11e6-9d8c-c9cb140a4ee5.png)

It just ignores the delay and additional character fields.

**Comment by onlykey** [comment]
Also works without the "Web Site" field for import to KeyPass
![image](https://cloud.githubusercontent.com/assets/18121756/15547833/90bff5b4-2273-11e6-9c1b-9dcde21d1fe2.png)

**Comment by rodgolpe** [comment]
Per our 7/16 hangout, I'm going to implement this as a pop-up after a label's info is submitted that asks: "Do you want to back up this info?"

**Comment by onlykey** [comment]
We have found a better approach to backup that will be included in Beta 4 of the firmware.
