### ISSUE TITLE
Pin setup, App and Firmware out of Sync in steps

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-Chrome-App#39]
The App appears to be one step ahead what the firmware is when setting up pins
![9-16 steps and firmware out of synce](https://cloud.githubusercontent.com/assets/9595840/18605106/e4c202e6-7c56-11e6-9aa9-60166fb922f5.PNG)

**Comment by rodgolpe** [comment]
Is this still an issue? Has it been reported in the wild?

**Comment by jaroszke** [comment]
I have not experienced this problem in a while and haven't had any reports of it. I'll close it.
