### ISSUE TITLE
Add new tab "Keys"

### ISSUE THREAD

**Issue by onlykey** [trustcrypto/OnlyKey-Chrome-App#42]
We now support 32 ECC keys and 4 RSA keys that can be used for SSH or GPG. We need a way for the user to set and wipe keys from their device. The format is very similar to the U2F Private and U2F certificate packets so that code may be copied and pasted with some changes. 

up to 32 ECC keys will be supported

Types
1 - ed25519
2 - NIST P256
3 - secp256k1

up to 4 RSA keys will be supported

Types
1 - 1024 bit key size
2 - 2048 bit key size

Slot 101-132 are for ECC, 1-4 are for RSA

So to set a 2048 bit RSA key to slot 1 of 4 there would be multiple packets
header - OKSETPRIV [239] - SLOT 1 - TYPE 2 - 57 bytes
header - OKSETPRIV [239] - SLOT 1 - TYPE 2 - 57 bytes
header - OKSETPRIV [239] - SLOT 1 - TYPE 2 - 57 bytes
header - OKSETPRIV [239] - SLOT 1 - TYPE 2 - 57 bytes
header - OKSETPRIV [239] - SLOT 1 - TYPE 2 - 29 bytes

And to set a 32 bit ECC ed25519 key to slot 24 of 32 there would be just one packet
header - OKSETPRIV [239] - SLOT 124 - TYPE 1 - 32 bytes

**Comment by onlykey** [comment]
This is what should appear on the Keys tab

Add Private Keys


ECC Key (32 bytes hex)

Type Dropdown Menu
1 - ed25519
2 - NIST P256
3 - secp256k1

Slot Dropdown Menu
1 - 32

Box

Checkbox 
“Set as backup key (Only one key may be set)”

Buttons
Save to OnlyKey, Wipe from OnlyKey


RSA Key (up to 2048 bytes hex)

Type Dropdown Menu
1 – 1024bit
2 – 2048bit

Slot Dropdown Menu
1 - 4

Box

Checkbox 
“Set as backup key (Only one key may be set)”

Buttons
Save to OnlyKey, Wipe from OnlyKey

**Comment by onlykey** [comment]
As mentioned in the first comment the ECC slots are 101 to 132, but the user can just be presented with 1 - 32. So add 100 to the slot value the user provides here. When the set as backup key is checked add 80 to the type value. So if type 1 and the user wants this to be the backup key the message sent to OnlyKey should be type 81.

**Comment by rodgolpe** [comment]
Makes sense. I'll ping you for clarification if needed.

**Comment by rodgolpe** [comment]
1. I thought OKSETPRIV was 239. These are the newest messages added as of the last app update:
OKGETPUBKEY: 236,
OKSIGN: 237,
OKWIPEPRIV: 238,
OKSETPRIV: 239,
OKDECRYPT: 240,
OKRESTORE: 241

2. How do I submit the "use as backup" bit?

3. Does OKWIPEPRIV accept a slot argument?

**Comment by onlykey** [comment]
@rodgolpe 
1 - Yep your right I just updated this in the issue
2 - Just add 0x80 to the type value if user wants it to be backup key, this just adds most sig bit, binary 10000000 
3 - Yes, OKWIPEPRIV[238] - SLOT 1-132, thats it

**Comment by onlykey** [comment]
@rodgolpe well it looks like in addition to the backup key checkbox we need three other checkboxes, we can just keep flipping bits of the first 4 bits of the byte:
backup key = type + 0x100
signature key = type + 0x80
decryption key = type + 0x40
authentication key = type + 0x10

**Comment by rodgolpe** [comment]
This feature has been merged to master.
