### ISSUE TITLE
Add new tab "Backup/Restore"

### ISSUE THREAD

**Issue by onlykey** [trustcrypto/OnlyKey-Chrome-App#43]
Backup

> Step 1. To begin backup ensure that you have a backup key set (in the keys tab) and that you have an offline copy of this backup key. The same key that you use to backup your OnlyKey will be required to restore your OnlyKey. 
> 
> Step 2. Click inside the box with your mouse and then hold the #1 button down on your OnlyKey for 5 seconds or more and then release. This will type out a backup of your OnlyKey slots and keys into the box.
> 
> Step 3. Once you see "-----END ONLYKEY KEY BACKUP-----" the backup of the OnlyKey slots and keys is complete. Select "Save file as" to save your encrypted backup to a secure location.
> 

Restore

> Step 1. In order to restore a backup file to your OnlyKey ensure you have loaded the same key you used to create the backup and set the key as backup the key. Also make sure your OnlyKey is unlocked and plugged in.
> 
> Step 2. Hold the #6 button down on your OnlyKey for 5 seconds or more and then release. The light will turn off on your OnlyKey and you must re-enter your PIN to unlock device into config mode. Open your backup file and select "Restore to OnlyKey".
> 
> Step 3. When you see the messages "Successfully loaded backup file" and "Remove and Reinsert OnlyKey to complete restore" the restore is complete. Remove and reinsert OnlyKey to complete restore.

**Comment by onlykey** [comment]
Created new message type OKRESTORE. The backup text file will have 56 characters and then a newline. Send one line from the backup text in each packet. The format is the same as the format used for OKSETU2FCERT. buffer[5] is set to FF if not the last packet, if it is the last packet buffer[5] is set to the size of last packet.

**Comment by rodgolpe** [comment]
Can definitely save a text file from a text input/textarea. I'll proceed with option 1.

**Comment by onlykey** [comment]
@rodgolpe Some more detail on the backup/restore tab. As mentioned above we have 3 step instructions for backup and for Restore. We could have the left side of the page have the Backup instructions, a text entry box where the OnlyKey will type out the backup, and a save as button to save the text file. On the right side we have the Restore instructions and a file box to select a backup file from the user's computer to restore. The backup file is already in a format where each line is 56 characters, the app just needs to parse and send these packets just like we do the OKSETU2F Cert packets - <header><OKRESTORE MSG> <FF or if last packet size of last packet> <Line from backup file>

**Comment by rodgolpe** [comment]
This has been implemented in branch https://github.com/trustcrypto/OnlyKey-Chrome-App/tree/backup-restore.

A couple of notes:

1. The restore success messages are not coming from the firmware; I simply output "Done!" when all the packets have been sent.
2. I cannot implement a proper "File save as..." dialog where the user can choose a file location or filename. We could add another text input for the filename, but choosing a file location doesn't seem to be possible in pure javascript.
