### ISSUE TITLE
Keys Feature - RSA Key no error for size less than 128 bytes

### ISSUE THREAD

**Issue by onlykey** [trustcrypto/OnlyKey-Chrome-App#46]
The ECC Key gives an error if you dont enter 32 bytes, it would be nice if RSA key field did this too. If possible require the right size for the type

1024 - size 128
2048 - size 256 bytes

**Comment by onlykey** [comment]
@rodgolpe

**Comment by rodgolpe** [comment]
I was wondering about that. We seem to have mixed use of "bit" and "byte" for RSA.
