### ISSUE TITLE
Key Feature - RSA Key loading issue

### ISSUE THREAD

**Issue by onlykey** [trustcrypto/OnlyKey-Chrome-App#47]
It looks like there are not enough packets being sent. 

to reproduce

try to load a 128 byte key

000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

type 1024
slot 1

Save to OnlyKey and look in serial monitor, it looks like only 1 or 2 packets are received it is still waiting for the rest

Received packetFFFFFFFFEF11000000000000000000000000000000000000000000000000000000000OKSETRSAPRIV MESSAGE RECEIVED
Slot = 0x1 Type = 0x1 

Once a full 128 bytes is received you see

Received packetFFFFFFFFEF11000000000000000000000000000000000000000000000000000000000OKSETRSAPRIV MESSAGE RECEIVED
Slot = 0x1 Type = 0x1 Received RSA Key of size 128
Erase Sector 0x23000 successful
RSA Key value =00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by onlykey** [comment]
@rodgolpe

**Comment by rodgolpe** [comment]
I pushed an adjustment to the packets for the OKSETPRIV message. To be honest, I'm coding kind of blind here, as I cannot get serial monitor to attach to an OnlyKey. My Mac is not exposing any ports except `cu.Bluetoot-Incoming-Port`. I spent a while troubleshooting but could not fix it.

Please test and post the results.

**Comment by rodgolpe** [comment]
Commit cf324f9397a67c52c9f7ee87292c901188c3039a reverts some of the changes made previously. Now RSA keys are expected to be hex PAIRS totaling 256 or 512 characters. Then, we convert each pair to a decimal before submitting 57 packets at a time. Thus, a 128 byte key should be 256 hex characters, which will be converted to 128 pairs, and sent in 3 messages (57 + 57 + 14) as decimals. A 256-byte should be 512 characters, split into 256 pairs, and sent in 5 messages (57 + 57 + 57 + 57 + 28).

**Comment by rodgolpe** [comment]
@onlykey From our Hangouts conversation, you said:

> So basically the way a user will use this and the way that we test it out is 1) Create a key in mailvelope (it requires setting a passcode) 2) go to export keys and copy past the private key into OnlyKey app 3) Enter passcode in app and select submit 4) App does the same thing as this http://kjur.github.io/jsrsasign/tool_pkcs5view.html to decrypt an pull out prime1(p) and prime2(q) 5) App sends this to OnlyKey just like it is currently sending the RSA key - The primes are exactly half the size of the key so 128byte (1024bit) rsa key will have primes of 64 bytes each.

I wanted to clarify that I'm adding a required passcode field, and still supporting 1024- and 2048-bit RSA keys. Also, does this affect ECC keys?

I looked at jsrsasign -- it's pretty sick! We don't need all of it, so I'm trying to figure out which features we need to port into the OK app. It's 10MB altogether, but seems modular enough.

**Comment by onlykey** [comment]
@rodgolpe So now that we are doing it this way we will still support 1024 and 2048bit keys but can also now support 3072 and 4096 keys. So just add these two additional types to the drop down under RSA keys. Type 1 = 1024, type 2 = 2048, type 3 = 3072, type 4 = 4096. You no longer have to check for the length, or restrict length in the box as the user is basically pasting a certificate now that is much longer. The jsrsasign will parse the cert. And yes it will need the passcode to decrypt the cert. 

For ECC keys I would like to do the same thing but not yet... jsrsasign does not parse ECC keys and they are not supported by OpenPGP.js yet. So no changes to ECC yet.

**Comment by rodgolpe** [comment]
I've got it wired up, but what I find is that Mailvelope PEMs are not going to work. jsrsasign depends on the key header being like:
```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-256-CBC,40555967F759530864FE022E257DE34E
```
Otherwise it throws a `substring of undefined` error. We can switch out the Mailvelope header, but I don't know enough about it to know whether `Proc-Type: 4,ENCRYPTED` etc apply.

Also, after getting the P and Q values, I'm still not sure how to send them. P in 1 packet and Q in the 2nd? In the sample key I'm using from the jsrsasign project, P = 0 and Q = 0. Doesn't seem right.

**Comment by rodgolpe** [comment]
As of https://github.com/trustcrypto/OnlyKey-Chrome-App/commit/e6d9db6020f6ac5d2a74a7a7b873ef5d013f63e6 keys are working with opengpg.js.
