### ISSUE TITLE
Key Tab cut off

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-Chrome-App#48]
The app on the Key tab cuts off, on Macbook pro non retina. No scroll bar, must tab to get to bottom.

![image](https://cloud.githubusercontent.com/assets/9595840/21873012/b32a1d56-d839-11e6-84e6-289706ebf6c0.png)

**Comment by rodgolpe** [comment]
Looks like there was a merge conflict committed. It was cleared moments after you pulled.
