### ISSUE TITLE
Displays Backup tab and initialize tab at same time

### ISSUE THREAD

**Issue by onlykey** [trustcrypto/OnlyKey-Chrome-App#51]
I already had the backup prompt up then inserted an uninitilized OK and got this

![image](https://cloud.githubusercontent.com/assets/18121756/22796891/37591f72-eeca-11e6-8dc9-0d10f45997b6.png)

Not a huge issue, if there is not an easy fix we can defer.

**Comment by rodgolpe** [comment]
This was fixed in https://github.com/trustcrypto/OnlyKey-Chrome-App/commit/e6d9db6020f6ac5d2a74a7a7b873ef5d013f63e6.
