### ISSUE TITLE
App stores backup info

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-Chrome-App#55]
After performing a backup and uplugging and re-inserting OK and unlocking.
The backup text area keeps the data in the field. This should be purged.

**Comment by jaroszke** [comment]
@rodgolpe 
Have you looked into this?

**Comment by rodgolpe** [comment]
This was fixed in https://github.com/trustcrypto/OnlyKey-Chrome-App/commit/e6d9db6020f6ac5d2a74a7a7b873ef5d013f63e6.
