### ISSUE TITLE
For Keys make sure to sanitize all sensitive values and console info

### ISSUE THREAD

**Issue by onlykey** [trustcrypto/OnlyKey-Chrome-App#58]
Need to make sure after we decrypt and send keys to OK we sanitize all the data on the app

**Comment by rodgolpe** [comment]
Anything in particular to do? In published versions of the app, there's no way to see the console. Also, the key data are not declared globally, so once the functions are done with them, they are not accessible via memory.

**Comment by rodgolpe** [comment]
The form was reset in https://github.com/trustcrypto/OnlyKey-Chrome-App/commit/e6d9db6020f6ac5d2a74a7a7b873ef5d013f63e6. Data still appear in the console for non-published versions.
