### ISSUE TITLE
RSA Private Key unable to save to OnlyKey

### ISSUE THREAD

**Issue by Jedimaster0** [trustcrypto/OnlyKey-Chrome-App#65]
I have generated a 1024, 2048, and a 4096 bit keys using ssh-keygen -rsa -b <length>. I have tried using no password and setting a password. However when I click the save button, it generates the below error message. I checked the documentation and watched the video you have posted. As far as I can tell, I have performed the same steps.

**Error Message:**
Error parsing RSA key: TypeError: Cannot read properly 'decrypt' of undefined.

**Comment by rodgolpe** [comment]
As of https://github.com/trustcrypto/OnlyKey-Chrome-App/releases/tag/v0.4-beta.0, a password is REQUIRED. If you are using the Chrome Webstore published version, it should have auto-updated. If not, please checkout the latest release.

That error means openpgpjs was unable to extract private key data from the key you pasted into the form. Please make sure you're generating valid PGP/GPG keys. We have documented a method that works with the Mailvelope extension: https://drive.google.com/file/d/0B_Bb-hXCnpYqb0ZDVFFRd1VLTE0  <-- goto p.31
