### ISSUE TITLE
Standalone app field history

### ISSUE THREAD

**Issue by jaroszke** [trustcrypto/OnlyKey-Chrome-App#74]
The passcode field on the key page seems to have field history enabled. This should be disabled
![screen shot 2017-12-03 at 8 53 42 pm](https://user-images.githubusercontent.com/9595840/33533163-4eff7044-d86d-11e7-9043-dbfbcbe8a884.png)

**Comment by onlykey** [comment]
@jaroszke This looks like Google Smartlock, I think this is enabled for all password fields but it requires user to save the password to remember it.

**Comment by onlykey** [comment]
@rodgolpe https://github.com/nwjs/nw.js/issues/5944
